### PR TITLE
Fix interface

### LINKED ISSUE #283: Argument default value inconsistence
We have an inconsistence between:

```php
function paginate($target, int $page = 1, int $limit = 10, array $options = [])
```
in https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/PaginatorInterface.php

and

```php
function paginate($target, int $page = 1, int $limit = null, array $options = [])
```
in https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Paginator.php

This is causing a problem in our Symfony bundle, since service is built using the interface, so it's impossible to use the "default" option. See [issue 689](https://github.com/KnpLabs/KnpPaginatorBundle/issues/689)

A possible solution is to change the interface, using `null` as default for `$limit`.
What we need to state is whether to put such change in a minor or in a major version.

### PR DESCRIPTION
**Pull request by garak**
Fix #283

### CODE REVIEW

File: src/Knp/Component/Pager/PaginatorInterface.php [hunk 1]
```diff
@@ -43,5 +43,5 @@ interface PaginatorInterface
      *                          array  $sortFieldAllowList sortable allow list for target fields being paginated
      * @throws \LogicException
      */
-    public function paginate($target, int $page = 1, int $limit = 10, array $options = []): PaginationInterface;
+    public function paginate($target, int $page = 1, int $limit = null, array $options = []): PaginationInterface;
```
Comment (mynameisbogdan) [inline src/Knp/Component/Pager/PaginatorInterface.php:46]: `@param int $limit` is intentional? 

now shouldn't it be `@param int|null $limit`?

Comment (garak) [reply src/Knp/Component/Pager/PaginatorInterface.php:46]: You're right
